### ISSUE TITLE
خطای 500

### ISSUE THREAD

**Issue by smahmoodh** [Alirezad07/X-Panel-SSH-User-Management#103]
روی اوبونتو 18 و 20 تست کردم خطا گرفتم.
وقتی دستورات نصب تموم میشه و آدرس رو توی مرورگر وارد میکنم خطای 500 میگیرم و یک ایمیل هم در مسیر /var/mail/root ایجاد میشه که محتوای اون متن زیر هست:
* Mark bundle as not supporting multiuse
> GET /fixer&jub=multi HTTP/1.1
> Host: ***.***.***.***:8025
> User-Agent: curl/7.68.0
> Accept: */*
> A: B
>

* HTTP 1.0, assume close after body
< HTTP/1.0 500 Internal Server Error
< Date: Sun, 21 May 2023 08:47:58 GMT
< Server: Apache/2.4.41 (Ubuntu)
< Content-Length: 0
< Connection: close
< Content-Type: text/html; charset=UTF-8
<
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
/var/www/html/cp/Libs/sh/kill.sh: line 6: =: command not found

فایلی هم که به خط 6 اون ایراد میگیره :

#!/bin/bash
#By Alireza

i=0
while [ $i -lt 20 ]; do
$cmd=$(curl -v -H "A: B" 'http://***.***.***.***:8025/fixer&jub=multi')
echo $cmd &
  sleep 3
  i=$(( i + 1 ))
done

اگه کسی میدونه مشکل چیه راهنمایی بکنه

**Comment by Alirezad07** [comment]
درود مراحل نصب را صحیح انجام نداده اید و postfix درست تنظیم نشده

**Comment by smahmoodh** [comment]
متوجه منظورتون نشدم.
ورژن 2.8 رو روی ubuntu 22 نصب کردم، باز شد ولی کاربرا میگفتن موقع استفاده، سرعت اینترنت نسبت به وقتی که یوزر رو با adduser  ساخته بودم کمتر شده.
الان اومدم به نسخه 3.1 بروزرسانی کردم پنل باز نمیشه و خطای 500 میده. توی روند بروزرسانی هم هیچ خطایی نمیگیرم.
الان نمیدونم باید چکار کنم. 
متن خطا 500 هم مجددا همون متنیه که توی پیام قبل فرستادم.

**Comment by Alirezad07** [comment]
درود بکاپ را به صورت دستی تهیه کنید  و سرور را ریبیلد کنید
در کانال تلگرامی آموزش هایی قرار داده شده است

**Comment by smahmoodh** [comment]
کانال تلگرام رو چک کردم ولی مشکلم برطرف نشد. روی سرور خام دستور نصب رو اجرا کردم روی هر 3 تا ورژن در دسترس اوبونتو ولی خطای 500 میده، فقط یکبار نسخه 2.8 روی اوبونتو 22 نصب شد که نسخه 3.1 پنل که منتشر شد بروزرسانی کردم دیگه بالا نیومد و با راه هایی که گفته بودن نصب مجدد postfix و بک آپ دستی و نصب مجدد هم درست نشد.
توی مسیر /var/www/html/cp/ فایل index.php رو ویرایش کردم و 3 خط کامنت رو فعال کردم و آدرس پنل رو زدم . این خطا رو نشون میده که شاید کمکی بکنه:

`Warning: Use of undefined constant HTTP_HOST - assumed 'HTTP_HOST' (this will throw an Error in a future version of PHP) in /var/www/html/cp/Config/define.php on line 3`

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'admin'@'localhost' (using password: YES) in /var/www/html/cp/Libs/Database.php:7 Stack trace: #0 /var/www/html/cp/Libs/Database.php(7): PDO->__construct() #1 /var/www/html/cp/Libs/Model.php(7): Database->__construct() #2 /var/www/html/cp/Models/Permission_Model.php(8): Model->__construct() #3 /var/www/html/cp/Libs/Bootstrap.php(27): Permission_Model->__construct() #4 /var/www/html/cp/index.php(16): Bootstrap->__construct() #5 {main} thrown in /var/www/html/cp/Libs/Database.php on line 7`

در تصویر زیر هم نصب postfix رو بدرستی نشون میده:
[http://howdoit.ir/screenshot.png](http://howdoit.ir/screenshot.png)

**Comment by smahmoodh** [comment]
حتی یکبار بصورت دستی mysql, apache و php رو نصب کردم و بعد پنل رو نصب کردم بازهم خطای 500 میداد.
ممنون میشم اگه راهنمایی کنید و ببخشید طولانی توضیح دادم.

**Comment by smahmoodh** [comment]
الان روی اوبونتو 20 نصب کردم بدون مشکل اومد بالا. اصلا عجیب و غریبه 😐
